title: <p align="center"> Shrinivas D </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume###.pdf">Resume</a> |
  <a href="###https://www.linkedin.com/in/name">LinkedIn</a> |
  <a href="https://github.com/gitname">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Machine learning & NLP related problems.
  For 10+ years.
  <br>
  </p>



theme: jekyll-theme-minimal
